bit-bots/bitbots_lowlevel

- bitbots_ros_control/src/dynamixel_hardware_interface.cpp
> ros_control: Show which motor has an overload error

- bitbots_buttons/src/bitbots_buttons/button_node.py
Adapted button usage to rules.
> use one button to penalize and one to unpenalize

- bitbots_ros_control/package.xml
- bitbots_ros_control/scripts/imu_interactive_marker.py
- bitbots_ros_control/scripts/reset_serials.py
- bitbots_ros_control/src/pressure_converter.py
This pull request updates all shebangs to python3 as we will discuss in our weekly.
> Update shebangs to python3

- bitbots_hardware_rqt/package.xml
- bitbots_ros_control/cfg/dynamixel_servo_hardware_interface_params.cfg
change shebang and or package.xml to work with python3
- ~~[ ] Update package version~~
- ~~[ ] Run linters~~
- ~~[ ] Write documentation~~
- ~~[x] Test on your machine~~
> dynamix reconfigure an package xml update for python3

- bitbots_ros_control/launch/ros_control.launch
- bitbots_ros_control/package.xml
- bitbots_ros_control/scripts/zero_on_button.py
Adds small script that listens to button press and zeros foot pressure sensors. Just a quality of life features
> zero on button

- bitbots_buttons/package.xml
- bitbots_buttons/src/bitbots_buttons/button_node.py
- bitbots_ros_control/include/bitbots_ros_control/bitfoot_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/button_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/dynamixel_servo_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/utils.h
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/dynamixel_servo_hardware_interface.cpp
- bitbots_ros_control/src/utils.cpp
- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
https://github.com/bit-bots/humanoid_league_msgs/pull/14
> refactor speak to audio

- bitbots_ros_control/README.md
- bitbots_ros_control/package.xml
small additional info to readme
> control: smal readme fix

- bitbots_ros_control/include/bitbots_ros_control/bitfoot_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/button_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/core_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/dynamixel_servo_hardware_interface.h
- bitbots_ros_control/include/bitbots_ros_control/servo_bus_interface.h
- bitbots_ros_control/include/bitbots_ros_control/wolfgang_hardware_interface.h
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/bitfoot_hardware_interface.cpp
- bitbots_ros_control/src/button_hardware_interface.cpp
- bitbots_ros_control/src/core_hardware_interface.cpp
- bitbots_ros_control/src/dynamixel_servo_hardware_interface.cpp
- bitbots_ros_control/src/node.cpp
- bitbots_ros_control/src/servo_bus_interface.cpp
- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
fixes some memory leaks in ros control for https://github.com/bit-bots/bitbots_lowlevel/issues/65
> ros control: fix memory leak

- bitbots_ros_control/package.xml
- bitbots_ros_control/src/node.cpp
- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
fixes https://github.com/bit-bots/bitbots_lowlevel/issues/63
> ros control: fix not working modes

- bitbots_ros_control/config/analyzers.yaml
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/bitfoot_hardware_interface.cpp
- bitbots_ros_control/src/node.cpp
Adds more diagnostics to ros control
> ros control: add more diagnostics

- bitbots_ros_control/package.xml
- bitbots_ros_control/src/imu_hardware_interface.cpp
Fix for writing the accel_gain and bias alpha
> fix writing of accel gain and bias alpha

- Jenkinsfile
- bitbots_buttons/.rdmanifest
- bitbots_buttons/rosdoc.yaml
- bitbots_hardware_rqt/.rdmanifest
- bitbots_hardware_rqt/rosdoc.yaml
- bitbots_ros_control/rosdoc.yaml
> add ci config and `.rdmanifest` files for bitbots_buttons and bitbots_hardware_rqt

- bitbots_ros_control/scripts/foot_pressure_tester.py
- bitbots_ros_control/scripts/led_error_blink.py
- bitbots_ros_control/scripts/send_sinus_command.py
https://github.com/bit-bots/bitbots_misc/pull/122
> change to new rate implementation

- bitbots_ros_control/scripts/foot_pressure_tester.py
- bitbots_ros_control/scripts/led_error_blink.py
- bitbots_ros_control/scripts/send_sinus_command.py
This reverts commit 43710fe8f7044077c08bc488ddf2421af214d9f8.
Reverts #90
> Revert "change to new rate implementation"

- bitbots_ros_control/include/bitbots_ros_control/pressure_converter.h
- bitbots_ros_control/scripts/pressure_calibration.py
- bitbots_ros_control/src/pressure_converter.cpp
Fixes pressure converter and calibration for ros 2 by adding the raw topic to another executor and running it in a new thread. Also fixes some minor issues introduced by the ros2 conversion script.
> Fixes foot pressure converter and calibration for ros2

- bitbots_ros_control/CMakeLists.txt
- bitbots_ros_control/launch/ros_control.launch
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/servo_bus_interface.cpp
- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
> ros control: fix not initialized variables

- bitbots_ros_control/config/wolfgang.yaml
> deactivate foot sensors

- bitbots_ros_control/launch/ros_control.launch
Follow-up on https://github.com/bit-bots/bitbots_lowlevel/pull/104.
> Disable pressure converter

- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
> make speach output better

- bitbots_ros_control/config/analyzers.yaml
- bitbots_ros_control/config/wolfgang.yaml
> fix issues with diagnostics

- bitbots_ros_control/src/node.cpp
> use event executor

- bitbots_ros_control/scripts/send_joint_command.py
The script was not migrated to ROS2 but can be useful for testing motors on the robot.
> Fix send_joint_command script

- bitbots_ros_control/config/rviz_imu.rviz
- bitbots_ros_control/config/rviz_pressure.rviz
- bitbots_ros_control/config/rviz_servos.rviz
- bitbots_ros_control/launch/viz_imu.launch
- bitbots_ros_control/launch/viz_pressure.launch
- bitbots_ros_control/launch/viz_servos.launch
Update the rviz configs to ros2.
> Update test launch files and configs to ros2

- bitbots_buttons/package.xml
- bitbots_ros_control/package.xml
to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html
> fix(package.xml): upgrade to version 3

- bitbots_buttons/CMakeLists.txt
- bitbots_buttons/package.xml
- The CI fails because some deps are missing in the package xml
> Fix button node deps

- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/src/imu_hardware_interface.cpp
We tuned the PIDs a bit and the walking etc. where much better.
Also fix small error related to the imu frame.
> Tune PID params

- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/include/bitbots_ros_control/servo_bus_interface.h
- bitbots_ros_control/src/servo_bus_interface.cpp
- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
- Add groups for different sets of ROM RAM register values
- Servos can be assigned to these groups (with a default groups if nothing was set)
> Add servo parameter groups

- bitbots_ros_control/config/wolfgang.yaml
Motors are flashed with a different baut rate. Need to adjust that in code.
> Set baud rate to 1000 instead of 4000

- bitbots_buttons/CMakeLists.txt
- bitbots_buttons/src/button_node.cpp
- Clean up
- Do localization reset on unpenalized
- Swap green and blue buttons
> Clean up button node
