bit-bots/bitbots_lowlevel

- bitbots_ros_control/src/dynamixel_hardware_interface.cpp
This parses the XML rosparam values into a list of (name, id)-tuples that can be sorted before the startup ping loop that checks the motors is started. This avoids confusion about the ping order (especially motor 19). Additionally, the name of the motor is also printed on ping errors.
> ros_control: sort joints from config before pinging them

- bitbots_ros_control/src/dynamixel_servo_hardware_interface.cpp
This fixes 2 things:
1. Wrong copy leading to goal and current positions being in the same memory
2. setting only current position if correctly read
> Fix: ros_control segfault

- bitbots_ros_control/package.xml
- bitbots_ros_control/src/node.cpp
- bitbots_ros_control/src/pressure_converter.py
Remove the include of the file removed in #38.
> ros_control: remove forgotten include

- bitbots_ros_control/config/controller.yaml
- bitbots_ros_control/config/rviz_interactive_imu.rviz
- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/launch/rviz_interactive_imu.launch
- bitbots_ros_control/package.xml
- bitbots_ros_control/scripts/imu_interactive_marker.py
- bitbots_ros_control/src/wolfgang_hardware_interface.cpp
This adds a new launch file, which starts RViz with an interactive marker, that provides IMU orientation. It can be used for testing, instead of using a real IMU
> ros_control: add interactive imu marker

- bitbots_ros_control/cfg/dynamixel_servo_hardware_interface_params.cfg
- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/include/bitbots_ros_control/dynamixel_servo_hardware_interface.h
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/dynamixel_servo_hardware_interface.cpp
add option to read the present PWM value from the servos. this helps debugging the problem of the servos not reaching their goal position, due to PID controller issues
-
> ros_control: add option to read current servo PWM values

- bitbots_ros_control/package.xml
- bitbots_ros_control/src/dynamixel_servo_hardware_interface.cpp
Previously, the pwm value would not be read if position, velocity and effort are being read. 
move the check for reading pwm out of the else statement
- ~[ ] Write documentation~
> ros_control: fix reading pwm value

- bitbots_ros_control/package.xml
- bitbots_ros_control/src/pressure_converter.cpp
just fixes a small bug which used two times the same value for the pressure sensor
> ros control: fix bug in pressure converter

- bitbots_ros_control/config/analyzers.yaml
- bitbots_ros_control/launch/ros_control.launch
- bitbots_ros_control/package.xml
Launches the system monitor on start up and adds analysers for its diagnostic messages.
https://github.com/bit-bots/bitbots_misc/pull/79
> ros control: add launching system monitor

- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/launch/pressure_converter.launch
- bitbots_ros_control/launch/ros_control.launch
- bitbots_ros_control/package.xml
Linux scheduling introduced problems when running full software stack. This PR limits the nodes to special cores via taskset, which solves the problem. Limited the control loop freq on 500Hz for now. Rather have it stable and a bit lower.
https://github.com/bit-bots/bitbots_lowlevel/issues/70
> ros control: fix scheduling problems

- bitbots_ros_control/config/analyzers.yaml
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/node.cpp
Warning was thrown to often for too small changes.
> control: make rate warning less sensitiv

- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/package.xml
- bitbots_ros_control/src/imu_hardware_interface.cpp
IMU firmware has small bug and does not remember one parameter. This will set them on start from config if defined. Will also generally be a nice thing
> control: fix imu filter params

- bitbots_ros_control/src/servo_bus_interface.cpp
Currently the overload message just printed an index of an array instead of the correct servo id. It is now changed to its name, as this is more convenient.
> ros_control: fix overload message

- bitbots_ros_control/CMakeLists.txt
- bitbots_ros_control/src/bitfoot_hardware_interface.cpp
- bitbots_ros_control/src/dynamixel_servo_hardware_interface.cpp
- bitbots_ros_control/src/leds_hardware_interface.cpp
- bitbots_ros_control/src/pressure_converter.cpp
- bitbots_ros_control/src/servo_bus_interface.cpp
This adds the -Wall -Werror -Wno-unused flags to ros_controll.
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on your machine~
> Use -Wall in ros_control

- bitbots_ros_control/config/wolfgang.yaml
- bitbots_ros_control/src/imu_hardware_interface.cpp
Head IMU was missing in config and therefore not read. Additionally, the imu topic was hardcoded instead of using the parameters.
> ros control: fix missing head imu and wrong imu topic

- bitbots_ros_control/src/servo_bus_interface.cpp
Changes read of torqueless_mode parameter back, as get_parameter_or does not seem to work as intended. This also means, the parameter needs to be set in every launch file and no longer has a default value.
> Fix torqueless mode parameter

- bitbots_ros_control/CMakeLists.txt
- bitbots_ros_control/launch/ros_control.launch
Currently the ros_control node is listed as "node" in the logs. This is not very helpful.
> Rename ros_control node from "node" to "ros_control"

- bitbots_ros_control/config/wolfgang.yaml
This reverts commit 8d6e9e81027f4c47f4cdb388cbd52efccda5616f because we can use them again.
> Revert "deactivate foot sensors"

- bitbots_ros_control/src/servo_bus_interface.cpp
This change gives the previous command to the motors after the servo connection was lost, for example because the power was switched off. This makes it possible to turn the power off and on again during a game without the need of connecting to a computer to restart the software.
> ros_control: set positions when servo connection is lost

- bitbots_buttons/CMakeLists.txt
- bitbots_buttons/package.xml
- bitbots_buttons/src/button_node.cpp
- bitbots_ros_control/CMakeLists.txt
- bitbots_ros_control/src/node.cpp
- Use released events executor binaries from rclcpp
PR because https://github.com/ros2/rclcpp/pull/2155 is merged and released.
> Use rclcpp events executor

- bitbots_ros_control/include/bitbots_ros_control/core_hardware_interface.h
- bitbots_ros_control/src/core_hardware_interface.cpp
This PR changes some things in the power status handling of ros_control. First of all, we now also read the "soft" power switch (software-controlled) status instead of only the physical switch. This data is also used to determine whether we should change the power status because we cannot change the physical power switch anyway. In addition, the CORE board is only written when it was read successfully. This resolves a `stack smashing detected` error we encountered when the CORE board was not available but we tried to write its registers.
> Fix write of power status to CORE

- bitbots_ros_control/config/wolfgang.yaml
Stop reading velocity and current as we do not use them in software.
> remove reading of velocity and current as it is currently not used

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- bitbots_buttons/docs/conf.py
- bitbots_ros_control/docs/conf.py
- bitbots_ros_control/scripts/led_error_blink.py
- pyproject.toml
Update to latest `pre-commit` settings as here: https://github.com/bit-bots/bitbots_behavior/pull/331
Follow up of: #134
> chore(pre-commit): update plugins and actions
